/// Flutter icons MesauringIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MesauringIcon
///      fonts:
///       - asset: fonts/MesauringIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MesauringIcon {
  MesauringIcon._();

  static const _kFontFam = 'MesauringIcon';
  static const String? _kFontPkg = null;

  static const IconData measuring_spoons =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
